added github action for charm release on charmhub.
canonical/charm-software-inventory-collector pull request #7
Opened 2023-03-24 21:09 UTC by gabrielcocenza

2023-03-27 09:02 UTC, rgildein requested changes
I think it should be done by re-usable workflow in bootstack-actions. The reason is that with reusable workflows we can make update in one place (bootstack-actions) and all charms will they inherit from it.

2023-03-27 19:44 UTC, gabrielcocenza commented
Thanks @rgildein. Please take a look at the canonical/bootstack-actions#13 before merging this PR.

2023-03-29 14:45 UTC, Pjack approved these changes

2023-03-31 10:10 UTC, esunar approved these changes

2023-03-31 13:28 UTC, rgildein approved these changes
Thanks

2023-03-31 18:06 UTC, merged